#!/bin/bash
sudo pacman -Rdd evolution
sudo pacman -Rdd evolution-ews
sudo pacman -Rdd evolution-help
sudo pacman -Rdd evolution-data-server
sudo pacman -Rdd gfbgraph
sudo pacman -Rdd gnome-boxes
sudo pacman -Rdd gnome-calendar
sudo pacman -Rdd gnome-contacts
sudo pacman -Rdd gnome-dictionary
sudo pacman -Rdd gnome-documents
sudo pacman -Rdd gnome-getting-started-docs
sudo pacman -Rdd gnome-initial-setup
sudo pacman -Rdd gnome-maps
sudo pacman -Rdd gnome-online-miners
sudo pacman -Rdd gnome-photos
sudo pacman -Rdd gnome-software
sudo pacman -Rdd gnome-user-docs
sudo pacman -Rdd gnome-user-share
sudo pacman -Rdd gnome-video-effects
sudo pacman -Rdd gnome-weather
sudo pacman -Rdd simple-scan
sudo pacman -Rdd totem
sudo pacman -Rdd tracker-miners
sudo pacman -Rdd accerciser
sudo pacman -Rdd brasero
sudo pacman -Rdd devhelp
sudo pacman -Rdd five-or-more
sudo pacman -Rdd four-in-a-row
sudo pacman -Rdd gnome-builder
sudo pacman -Rdd gnome-devel-docs
sudo pacman -Rdd gnome-kiotski
sudo pacman -Rdd gnome-mahjongg
sudo pacman -Rdd gnome-recipes
sudo pacman -Rdd gnome-robots
sudo pacman -Rdd gnome-sudoku
sudo pacman -Rdd gnome-taquin
sudo pacman -Rdd gnome-tetravex
sudo pacman -Rdd hitori
sudo pacman -Rdd iagno
sudo pacman -Rdd lightsoff
sudo pacman -Rdd polari
sudo pacman -Rdd quadrapassel
sudo pacman -Rdd swell-foop
sudo pacman -Rdd tali
