#!/bin/bash
set -ex

[[ $UID != 0 ]] && exec sudo -E "$(readlink -f "$0")" "$@"

up() {
    #killall wpa_supplicant dhcpcd || true
    ip netns add physical
    ip -n physical link add us1 type wireguard
    ip -n physical link set us1 netns 1
    wg setconf us1 /etc/wireguard/us1.conf
    ip addr add 192.168.0.1/32 dev us1
    ip link set wlan0 down
    iw phy phy0 set netns name physical
    #ip netns exec physical dhcpcd -b wlan0
    #ip netns exec physical wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-wlan0.conf -iwlan0
    ip link set wlan0 up
    ip link set us1 up
    ip route add default dev us1
    wg-quick /etc/wireguard/us1.conf
}

down() {
    #killall wpa_supplicant dhcpcd || true
    ip -n physical link set wlan0 down
    ip netns exec physical iw phy phy0 set netns 1
    ip link del us1
    ip netns del physical
    dhcpcd -b wlan0
    #wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-wlan0.conf -iwlan0
}

execi() {
    exec ip netns exec physical sudo -E -u \#${SUDO_UID:-$(id -u)} -g \#${SUDO_GID:-$(id -g)} -- "$@"
}

command="$1"
shift

case "$command" in
    up) up "$@" ;;
    down) down "$@" ;;
    exec) execi "$@" ;;
    *) echo "Usage: $0 up|down|exec" >&2; exit 1 ;;
esac
